paperscore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ranking.urls', namespace='ranking')),
]

ranking/urls.py
from django.urls import path

from .views import main_page, paper_rank, PaperListView, PaperDetailView

app_name = 'ranking'
urlpatterns = [
    path('rank/', paper_rank, name='rank'),
    path('papers/', PaperListView.as_view(), name='papers'),
    path('paper/<int:pk>/<slug:slug>/', PaperDetailView.as_view(), name='paper'),
    path('', main_page, name='main'),
]

ranking/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify


class Publisher(models.Model):
    name = models.CharField(max_length=80, blank=False)

    def __str__(self):
        return '<Publisher %s>' % self.name


class Paper(models.Model):
    title = models.CharField(max_length=140, blank=False)
    slug = models.SlugField(max_length=50, blank=True)  # auto-generated from title
    author = models.CharField(max_length=255, blank=False)
    year = models.IntegerField(null=False)
    publisher = models.ForeignKey(Publisher, on_delete=models.PROTECT)
    abstract = models.TextField(blank=True)
    score = models.FloatField(null=False)
    registered = models.DateTimeField(auto_now_add=True)

    def short_author(self):
        return self.author.split(' ')[0] + ' et al.'

    def __str__(self):
        return '"%s" by %s' % (self.title, self.short_author())


def length_slugify(value, length):
    slug = slugify(value)[:length]
    if '-' in slug:
        if slug[-1] == '-':
            return slug[:-1]
        else:
            return '-'.join(slug.split('-')[:-1])
    else:
        return slug


@receiver(pre_save, sender=Paper)
def autofill_slug(sender, **kwargs):
    instance = kwargs['instance']
    if not instance.slug:
        instance.slug = length_slugify(instance.title, 50)

ranking/views.py
from django.db.models import Sum, Q
from django.http import HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView

from .models import Paper


def annotate_ranking(queryset):
    for i, publisher in enumerate(queryset):
        publisher['ranking'] = i + 1
    return queryset


def main_page(request):
    recent_paper = Paper.objects.order_by('-registered', '-pk')[:10]
    return render(request, 'ranking/main.html',
                  {'recent_paper': recent_paper})


def paper_rank(request):
    try:
        year = int(request.GET['year'])
    except (KeyError, ValueError):
        year = timezone.now().year

    this_year = Paper.objects.filter(year=year) \
        .values('publisher', 'publisher__name').annotate(score_sum=Sum('score')) \
        .order_by('-score_sum', 'publisher__name')
    last_year = Paper.objects.filter(year=year-1) \
        .values('publisher', 'publisher__name').annotate(score_sum=Sum('score')) \
        .order_by('-score_sum', 'publisher__name')

    this_year = annotate_ranking(this_year)
    last_year = annotate_ranking(last_year)
    last_year_dict = {}
    for publisher in last_year:
        last_year_dict[publisher['publisher__name']] = publisher

    for publisher in this_year:
        try:
            last_year_publisher = last_year_dict[publisher['publisher__name']]
            publisher['delta'] = last_year_publisher['ranking'] - publisher['ranking']
            publisher['delta_abs'] = abs(publisher['delta'])
        except KeyError:
            publisher['delta'] = 0

    return render(request, 'ranking/rank.html',
                  {'publishers': this_year, 'year': year})


class PaperListView(ListView):
    model = Paper

    template_name = 'ranking/paper_list.html'
    context_object_name = 'papers'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query is not None:
            return Paper.objects.filter(
                Q(title__icontains=query) |
                Q(author__icontains=query) |
                Q(abstract__contains=query) |
                Q(publisher__name__icontains=query)).order_by('-id')
        else:
            return Paper.objects.order_by('-id')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['query'] = self.request.GET.get('query')
        return context


class PaperDetailView(DetailView):
    model = Paper
    template_name = 'ranking/paper_detail.html'
    context_object_name = 'paper'

    def __init__(self):
        super().__init__()
        self.redirect = None

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        url_slug = self.kwargs.get(self.slug_url_kwarg)
        obj_slug = getattr(obj, self.get_slug_field())
        if url_slug != obj_slug:
            self.redirect = reverse('ranking:paper',
                                    kwargs={'pk': obj.pk, 'slug': obj_slug})
        return obj

    def render_to_response(self, context, **response_kwargs):
        if self.redirect:
            return redirect(self.redirect)
        return super().render_to_response(context, **response_kwargs)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans|Orbitron:400,300,600|Raleway" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% block head %}{% endblock %}
</head>

<body>
<header id="header-container" class="header">
  <div id="heading">
    <a id="logo-link" href="{% url 'ranking:main' %}">
      <div id="logo">
        paperrank
      </div>
    </a>
    <div id="nav">
      <a href="{% url 'ranking:main' %}" class="nav-item">MAIN</a>
      <a href="{% url 'ranking:rank' %}" class="nav-item">RANK</a>
      <a href="{% url 'ranking:papers' %}" class="nav-item">PAPERS</a>
    </div>
  </div>
</header>
<div class="container">
  {% block contents %}{% endblock %}
</div>
<footer>
  <div id="copyright-paper">
    Unless otherwise noted, all papers on this site are copyrighted material of the respective owners.
  </div>
  <div id="copyright-general">
    Copyright 2018 Frank Yang
  </div>
</footer>
</body>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
        let isShadowed = false;
        const header = document.getElementById("header-container");
        const scrollHandler = function() {
            let top = window.pageYOffset || document.documentElement.scrollTop;
            if (!isShadowed && top > 0) {
                header.classList.add('shadowed-header');
                isShadowed = true;
            }
            else if (isShadowed && top === 0) {
                header.classList.remove('shadowed-header');
                isShadowed = false;
            }
        };
        document.addEventListener('scroll', scrollHandler);
    });
</script>
</html>

templates/ranking/main.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block title %}paperrank{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
{% endblock %}
{% block contents %}
  <h3>Welcome to paperrank</h3>
  <section id="intro">
    paperrank is a site where you can find out each publisher's papers, its respective ranking, and fluctuation of it.<br>
    you can find each publishers' ranking in the <a href="{% url 'ranking:rank' %}">ranking</a> section,
    and all the papers on this site can be found in the <a href="{% url 'ranking:papers' %}">papers</a> section.
  </section>
  <h3>Recently registered papers</h3>
  <ul>
  {% for paper in recent_paper %}
    <li>
      <a href="{% url 'ranking:paper' paper.pk paper.slug %}">{{ paper.title }}</a>
       from {{ paper.publisher.name }} was registered {{ paper.registered|naturalday }}
    </li>
  {% endfor %}
  </ul>
{% endblock %}

templates/ranking/paper_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/paper_detail.css' %}">
{% endblock %}
{% block title %}{{ paper.title }} | paperrank {% endblock %}
{% block contents %}
  <h3>{{ paper.title }}</h3>
  <hr/>
  <div class="detail">
    <div class="row">
      <div class="six columns field">
        <div class="field-title">Author</div>
        <div class="field-value">{{ paper.author }}</div>
      </div>
      <div class="six columns field">
        <div class="field-title">Published Year</div>
        <div class="field-value">{{ paper.year }}</div>
      </div>
    </div>
    <div class="row">
      <div class="twelve columns field">
        <div class="field-title">Publisher</div>
        <div class="field-value">{{ paper.publisher.name }}</div>
      </div>
    </div>
    <div class="row">
      <div class="twelve columns field">
        <div class="field-title">Abstract</div>
        <div class="field-value">{{ paper.abstract }}</div>
      </div>
    </div>
  </div>
{% endblock %}

templates/ranking/paper_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Papers | paperrank{% endblock %}
{% block head %}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/paper_list.css' %}">
{% endblock %}
{% block contents %}
  <div id="title">
    <div id="title-heading"><h1>Papers</h1></div>
    <form id="search" action="" method="GET">
      <div class="input-field">
        <i class="material-icons">search</i>
        <input type="text" name="query" id="query"
               placeholder="Search papers" {% if query %} value="{{ query }}" {% endif %}/>
      </div>
    </form>
  </div>
  <hr/>
  <table id="papers" class="u-full-width">
    <thead>
      <tr>
        <th class="publisher">Publisher</th>
        <th class="title">Title</th>
        <th class="author">Author</th>
      </tr>
    </thead>
    <tbody>
    {% for paper in papers %}
      <tr>
        <td>{{ paper.publisher.name }}</td>
        <td class="title">
          <a href="{% url 'ranking:paper' paper.pk paper.slug %}">{{ paper.title }}</a>
        </td>
        <td>{{ paper.short_author }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <div class="row page">
    <div class="three columns prev">
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">&lt;&lt; {{ page_obj.previous_page_number }}</a>
      {% endif %}
      &nbsp;
    </div>
    <div class="six columns current">{{ page_obj.number }}</div>
    <div class="three columns next">
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }} >></a>
      {% endif %}
      &nbsp;
    </div>
  </div>
{% endblock %}

templates/ranking/rank.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Ranking | paperrank{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/rank.css' %}">
{% endblock %}
{% block contents %}
  <h1>Ranking</h1>
  <div class="row years">
  <div class="three columns prev">
    <a href="{% url 'ranking:rank' %}?year={{ year|add:-1 }}"><< {{ year|add:-1 }}</a>
  </div>
  <div class="six columns current">{{ year }}</div>
  <div class="three columns next">
    <a href="{% url 'ranking:rank' %}?year={{ year|add:1 }}">{{ year|add:1 }} >></a>
  </div>
  </div>
  <hr>
  {% if publishers %}
  <table id="rank" class="u-full-width">
    <thead>
      <tr>
        <th>Ranking</th>
        <th>Publisher Name</th>
        <th>Score</th>
        <th class="delta">Delta</th>
      </tr>
    </thead>
    <tbody>
    {% for publisher in publishers %}
      <tr>
        <td>{{ publisher.ranking }}</td>
        <td>{{ publisher.publisher__name }}</td>
        <td>{{ publisher.score_sum|floatformat:2 }}</td>
        <td class="delta">
          {% if publisher.delta > 0 %}
            <div class="gt">▲ {{ publisher.delta_abs }}</div>
          {% elif publisher.delta < 0 %}
            <div class="lt">▼ {{ publisher.delta_abs }}</div>
          {% else %}
            <div class="eq">-</div>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
    <div class="row">
      <div class="twelve columns no-data">NO DATA AVAILABLE</div>
    </div>
  {% endif %}
{% endblock %}